# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  username: root
  password: 123456

development:
  <<: *default
  database: development_api

test:
  <<: *default
  database: test_api

production:
  <<: *default
  database: production_api
