# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aca5e9dde2c0b31369894236c5905d097230755e2f3a53b1a4be8ec8eedf5efcf49e747c25eb46cd111fd8b19c8112e88a8b74485b67e29181c42dfe187d0455

test:
  secret_key_base: e775cb2a83764be3fd005e7b66473d0e35b197b6795fbf823720eb429ed551e1db49cd5c2f6d8a7dd0d584e880b1030a450596fc98f313b0db1021e687165d5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
